/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as PublicoRouteImport } from './routes/publico'
import { Route as ProjecaoRouteImport } from './routes/projecao'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as MetaAdsRouteImport } from './routes/meta-ads'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as JarvisRouteImport } from './routes/jarvis'
import { Route as InteligenciaIaRouteImport } from './routes/inteligencia-ia'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as FluxosRouteImport } from './routes/fluxos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FilaRouteImport } from './routes/fila'
import { Route as ComprovantesIaRouteImport } from './routes/comprovantes-ia'
import { Route as ChatOficialRouteImport } from './routes/chat-oficial'
import { Route as ChatBaileysRouteImport } from './routes/chat-baileys'
import { Route as AgentesIaRouteImport } from './routes/agentes-ia'
import { Route as AgendamentosRouteImport } from './routes/agendamentos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhookWhatsappRouteImport } from './routes/api/public/webhook-whatsapp'
import { Route as ApiPublicMessageDispatcherRouteImport } from './routes/api/public/message-dispatcher'
import { Route as ApiPublicFunnelSchedulerRouteImport } from './routes/api/public/funnel-scheduler'
import { Route as ApiPublicEvolutionStatusRouteImport } from './routes/api/public/evolution-status'

const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicoRoute = PublicoRouteImport.update({
  id: '/publico',
  path: '/publico',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjecaoRoute = ProjecaoRouteImport.update({
  id: '/projecao',
  path: '/projecao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaAdsRoute = MetaAdsRouteImport.update({
  id: '/meta-ads',
  path: '/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const JarvisRoute = JarvisRouteImport.update({
  id: '/jarvis',
  path: '/jarvis',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaIaRoute = InteligenciaIaRouteImport.update({
  id: '/inteligencia-ia',
  path: '/inteligencia-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxosRoute = FluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FilaRoute = FilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprovantesIaRoute = ComprovantesIaRouteImport.update({
  id: '/comprovantes-ia',
  path: '/comprovantes-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatOficialRoute = ChatOficialRouteImport.update({
  id: '/chat-oficial',
  path: '/chat-oficial',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatBaileysRoute = ChatBaileysRouteImport.update({
  id: '/chat-baileys',
  path: '/chat-baileys',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesIaRoute = AgentesIaRouteImport.update({
  id: '/agentes-ia',
  path: '/agentes-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosRoute = AgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookWhatsappRoute =
  ApiPublicWebhookWhatsappRouteImport.update({
    id: '/api/public/webhook-whatsapp',
    path: '/api/public/webhook-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMessageDispatcherRoute =
  ApiPublicMessageDispatcherRouteImport.update({
    id: '/api/public/message-dispatcher',
    path: '/api/public/message-dispatcher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFunnelSchedulerRoute =
  ApiPublicFunnelSchedulerRouteImport.update({
    id: '/api/public/funnel-scheduler',
    path: '/api/public/funnel-scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEvolutionStatusRoute =
  ApiPublicEvolutionStatusRouteImport.update({
    id: '/api/public/evolution-status',
    path: '/api/public/evolution-status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/agentes-ia': typeof AgentesIaRoute
  '/chat-baileys': typeof ChatBaileysRoute
  '/chat-oficial': typeof ChatOficialRoute
  '/comprovantes-ia': typeof ComprovantesIaRoute
  '/fila': typeof FilaRoute
  '/financeiro': typeof FinanceiroRoute
  '/fluxos': typeof FluxosRoute
  '/funil': typeof FunilRoute
  '/inteligencia-ia': typeof InteligenciaIaRoute
  '/jarvis': typeof JarvisRoute
  '/leads': typeof LeadsRoute
  '/meta-ads': typeof MetaAdsRoute
  '/overview': typeof OverviewRoute
  '/produtos': typeof ProdutosRoute
  '/projecao': typeof ProjecaoRoute
  '/publico': typeof PublicoRoute
  '/tarefas': typeof TarefasRoute
  '/transacoes': typeof TransacoesRoute
  '/api/public/evolution-status': typeof ApiPublicEvolutionStatusRoute
  '/api/public/funnel-scheduler': typeof ApiPublicFunnelSchedulerRoute
  '/api/public/message-dispatcher': typeof ApiPublicMessageDispatcherRoute
  '/api/public/webhook-whatsapp': typeof ApiPublicWebhookWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/agentes-ia': typeof AgentesIaRoute
  '/chat-baileys': typeof ChatBaileysRoute
  '/chat-oficial': typeof ChatOficialRoute
  '/comprovantes-ia': typeof ComprovantesIaRoute
  '/fila': typeof FilaRoute
  '/financeiro': typeof FinanceiroRoute
  '/fluxos': typeof FluxosRoute
  '/funil': typeof FunilRoute
  '/inteligencia-ia': typeof InteligenciaIaRoute
  '/jarvis': typeof JarvisRoute
  '/leads': typeof LeadsRoute
  '/meta-ads': typeof MetaAdsRoute
  '/overview': typeof OverviewRoute
  '/produtos': typeof ProdutosRoute
  '/projecao': typeof ProjecaoRoute
  '/publico': typeof PublicoRoute
  '/tarefas': typeof TarefasRoute
  '/transacoes': typeof TransacoesRoute
  '/api/public/evolution-status': typeof ApiPublicEvolutionStatusRoute
  '/api/public/funnel-scheduler': typeof ApiPublicFunnelSchedulerRoute
  '/api/public/message-dispatcher': typeof ApiPublicMessageDispatcherRoute
  '/api/public/webhook-whatsapp': typeof ApiPublicWebhookWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/agentes-ia': typeof AgentesIaRoute
  '/chat-baileys': typeof ChatBaileysRoute
  '/chat-oficial': typeof ChatOficialRoute
  '/comprovantes-ia': typeof ComprovantesIaRoute
  '/fila': typeof FilaRoute
  '/financeiro': typeof FinanceiroRoute
  '/fluxos': typeof FluxosRoute
  '/funil': typeof FunilRoute
  '/inteligencia-ia': typeof InteligenciaIaRoute
  '/jarvis': typeof JarvisRoute
  '/leads': typeof LeadsRoute
  '/meta-ads': typeof MetaAdsRoute
  '/overview': typeof OverviewRoute
  '/produtos': typeof ProdutosRoute
  '/projecao': typeof ProjecaoRoute
  '/publico': typeof PublicoRoute
  '/tarefas': typeof TarefasRoute
  '/transacoes': typeof TransacoesRoute
  '/api/public/evolution-status': typeof ApiPublicEvolutionStatusRoute
  '/api/public/funnel-scheduler': typeof ApiPublicFunnelSchedulerRoute
  '/api/public/message-dispatcher': typeof ApiPublicMessageDispatcherRoute
  '/api/public/webhook-whatsapp': typeof ApiPublicWebhookWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamentos'
    | '/agentes-ia'
    | '/chat-baileys'
    | '/chat-oficial'
    | '/comprovantes-ia'
    | '/fila'
    | '/financeiro'
    | '/fluxos'
    | '/funil'
    | '/inteligencia-ia'
    | '/jarvis'
    | '/leads'
    | '/meta-ads'
    | '/overview'
    | '/produtos'
    | '/projecao'
    | '/publico'
    | '/tarefas'
    | '/transacoes'
    | '/api/public/evolution-status'
    | '/api/public/funnel-scheduler'
    | '/api/public/message-dispatcher'
    | '/api/public/webhook-whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamentos'
    | '/agentes-ia'
    | '/chat-baileys'
    | '/chat-oficial'
    | '/comprovantes-ia'
    | '/fila'
    | '/financeiro'
    | '/fluxos'
    | '/funil'
    | '/inteligencia-ia'
    | '/jarvis'
    | '/leads'
    | '/meta-ads'
    | '/overview'
    | '/produtos'
    | '/projecao'
    | '/publico'
    | '/tarefas'
    | '/transacoes'
    | '/api/public/evolution-status'
    | '/api/public/funnel-scheduler'
    | '/api/public/message-dispatcher'
    | '/api/public/webhook-whatsapp'
  id:
    | '__root__'
    | '/'
    | '/agendamentos'
    | '/agentes-ia'
    | '/chat-baileys'
    | '/chat-oficial'
    | '/comprovantes-ia'
    | '/fila'
    | '/financeiro'
    | '/fluxos'
    | '/funil'
    | '/inteligencia-ia'
    | '/jarvis'
    | '/leads'
    | '/meta-ads'
    | '/overview'
    | '/produtos'
    | '/projecao'
    | '/publico'
    | '/tarefas'
    | '/transacoes'
    | '/api/public/evolution-status'
    | '/api/public/funnel-scheduler'
    | '/api/public/message-dispatcher'
    | '/api/public/webhook-whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentosRoute: typeof AgendamentosRoute
  AgentesIaRoute: typeof AgentesIaRoute
  ChatBaileysRoute: typeof ChatBaileysRoute
  ChatOficialRoute: typeof ChatOficialRoute
  ComprovantesIaRoute: typeof ComprovantesIaRoute
  FilaRoute: typeof FilaRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FluxosRoute: typeof FluxosRoute
  FunilRoute: typeof FunilRoute
  InteligenciaIaRoute: typeof InteligenciaIaRoute
  JarvisRoute: typeof JarvisRoute
  LeadsRoute: typeof LeadsRoute
  MetaAdsRoute: typeof MetaAdsRoute
  OverviewRoute: typeof OverviewRoute
  ProdutosRoute: typeof ProdutosRoute
  ProjecaoRoute: typeof ProjecaoRoute
  PublicoRoute: typeof PublicoRoute
  TarefasRoute: typeof TarefasRoute
  TransacoesRoute: typeof TransacoesRoute
  ApiPublicEvolutionStatusRoute: typeof ApiPublicEvolutionStatusRoute
  ApiPublicFunnelSchedulerRoute: typeof ApiPublicFunnelSchedulerRoute
  ApiPublicMessageDispatcherRoute: typeof ApiPublicMessageDispatcherRoute
  ApiPublicWebhookWhatsappRoute: typeof ApiPublicWebhookWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publico': {
      id: '/publico'
      path: '/publico'
      fullPath: '/publico'
      preLoaderRoute: typeof PublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projecao': {
      id: '/projecao'
      path: '/projecao'
      fullPath: '/projecao'
      preLoaderRoute: typeof ProjecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-ads': {
      id: '/meta-ads'
      path: '/meta-ads'
      fullPath: '/meta-ads'
      preLoaderRoute: typeof MetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jarvis': {
      id: '/jarvis'
      path: '/jarvis'
      fullPath: '/jarvis'
      preLoaderRoute: typeof JarvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia-ia': {
      id: '/inteligencia-ia'
      path: '/inteligencia-ia'
      fullPath: '/inteligencia-ia'
      preLoaderRoute: typeof InteligenciaIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxos': {
      id: '/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof FluxosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fila': {
      id: '/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof FilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprovantes-ia': {
      id: '/comprovantes-ia'
      path: '/comprovantes-ia'
      fullPath: '/comprovantes-ia'
      preLoaderRoute: typeof ComprovantesIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-oficial': {
      id: '/chat-oficial'
      path: '/chat-oficial'
      fullPath: '/chat-oficial'
      preLoaderRoute: typeof ChatOficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-baileys': {
      id: '/chat-baileys'
      path: '/chat-baileys'
      fullPath: '/chat-baileys'
      preLoaderRoute: typeof ChatBaileysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes-ia': {
      id: '/agentes-ia'
      path: '/agentes-ia'
      fullPath: '/agentes-ia'
      preLoaderRoute: typeof AgentesIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos': {
      id: '/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook-whatsapp': {
      id: '/api/public/webhook-whatsapp'
      path: '/api/public/webhook-whatsapp'
      fullPath: '/api/public/webhook-whatsapp'
      preLoaderRoute: typeof ApiPublicWebhookWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/message-dispatcher': {
      id: '/api/public/message-dispatcher'
      path: '/api/public/message-dispatcher'
      fullPath: '/api/public/message-dispatcher'
      preLoaderRoute: typeof ApiPublicMessageDispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/funnel-scheduler': {
      id: '/api/public/funnel-scheduler'
      path: '/api/public/funnel-scheduler'
      fullPath: '/api/public/funnel-scheduler'
      preLoaderRoute: typeof ApiPublicFunnelSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution-status': {
      id: '/api/public/evolution-status'
      path: '/api/public/evolution-status'
      fullPath: '/api/public/evolution-status'
      preLoaderRoute: typeof ApiPublicEvolutionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentosRoute: AgendamentosRoute,
  AgentesIaRoute: AgentesIaRoute,
  ChatBaileysRoute: ChatBaileysRoute,
  ChatOficialRoute: ChatOficialRoute,
  ComprovantesIaRoute: ComprovantesIaRoute,
  FilaRoute: FilaRoute,
  FinanceiroRoute: FinanceiroRoute,
  FluxosRoute: FluxosRoute,
  FunilRoute: FunilRoute,
  InteligenciaIaRoute: InteligenciaIaRoute,
  JarvisRoute: JarvisRoute,
  LeadsRoute: LeadsRoute,
  MetaAdsRoute: MetaAdsRoute,
  OverviewRoute: OverviewRoute,
  ProdutosRoute: ProdutosRoute,
  ProjecaoRoute: ProjecaoRoute,
  PublicoRoute: PublicoRoute,
  TarefasRoute: TarefasRoute,
  TransacoesRoute: TransacoesRoute,
  ApiPublicEvolutionStatusRoute: ApiPublicEvolutionStatusRoute,
  ApiPublicFunnelSchedulerRoute: ApiPublicFunnelSchedulerRoute,
  ApiPublicMessageDispatcherRoute: ApiPublicMessageDispatcherRoute,
  ApiPublicWebhookWhatsappRoute: ApiPublicWebhookWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
