DO $$
BEGIN
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE leads; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE lead_tags; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE scheduled_messages; EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;
ALTER TABLE messages REPLICA IDENTITY FULL;
ALTER TABLE leads REPLICA IDENTITY FULL;
ALTER TABLE lead_tags REPLICA IDENTITY FULL;
ALTER TABLE scheduled_messages REPLICA IDENTITY FULL;